# Generated by Django 5.1.1 on 2024-09-07 11:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="description_kor",
            new_name="description_ko",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="product_name_kor",
            new_name="product_name_ko",
        ),
    ]
